menu:
# - {name: 'people', url: '/people'}
- {name: 'Research', url: '/research'}
- {name: 'Hobbies', url: '/hobby'}
- {name: 'Publications', url: '/publications'}
# - {name: 'courses', url: '/courses'}
- {name: 'CV', url: '/cv'}
- {name: 'Contact', url: '/contact'}

contacts:
- {name: 'Xiangyu', title: 'Doctoral student', department: 'Biosystems Engineering', 
institution: 'Zhejiang University', 
institution_address: '866 Yuhangtang Road, Hangzhou, Zhejiang Province, China',
 phone: '+86 152 0642 4953', email: 'luxyzju@zju.edu.cn',  
 image: 'assets/img/IMG_0602.jpg'}
